version: "3"

services:

  app:
    image: sintia
    container_name: sintia_app_container
    restart: always
    ports:
      - "8081:8081"
    working_dir: /app

  postgres:
    image: postgres
    container_name: sintia_postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "example"
      POSTGRES_USER: "sintia"
      POSTGRES_DB: "sintia"
      PGDATA: "/var/lib/postgresql/data/"

  pgadmin:
    image: dpage/pgadmin4
    container_name: sintia_postgres_admin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "example"

